#!/bin/sh

#
# Run parameters
export TMPL=$HADOOP_HOME/../conf/conf-personal/genepool/
export HADOOP_LOG_DIR=$SCRATCH/logs/
export HADOOP_PID_DIR=$SCRATCH/logs/pids/
export EXT="-nohdfs"

if [ ! -e $HADOOP_CONF_DIR ] ; then
  IP=$( host $(hostname)|sed 's/.* //')
  mkdir $HADOOP_CONF_DIR
  for file in "mapred" "core" "hdfs"; do
    cat $TMPL/$file-site${EXT}.xml.tmpl | \
          sed "s|%IP%|$IP|"| \
          sed "s|%SCRATCH%|$SCRATCH|"| \
          sed "s|%USER%|$USER|" > $HADOOP_CONF_DIR/$file-site.xml
  done
fi

hadoop-daemon.sh start jobtracker

